# RepoDynamics Meta Configuration
# -------------------------------
# This file contains the base configurations for RepoDynamics.
# All available configurations and their default values are listed below.
# If you don't want to change any of the default values, you can delete this file.


# The single root key of this file:
repodynamics:
  # Number of days to keep the cache data for meta contents:
  cache_retention_days:
    # for extended contents (defined in `extensions.yaml`) retrieved from other repositories:
    extensions: 1
    # for data retrieved from web-APIs, such as GitHub repo/users data, software versions, publications etc.:
    api: 1
